In [85]:
import numpy as np

A = np.array([[1, 2], [3, 6]])
#print(A)

A_val_p =np.linalg.eig(A)[0]
print(A_val_p)

vec1=[np.linalg.eig(A)[1][0][0],np.linalg.eig(A)[1][1][0]]
vec2=[np.linalg.eig(A)[1][0][1],np.linalg.eig(A)[1][1][1]]
print(vec1)
print(vec2)
print(np.dot(A,vec1))
print(np.dot(7,vec2))

A_vec_p = np.array([vec1,vec2])

#A_vec_p =np.linalg.eig(A)[1]
#print(A_vec_p)

D=np.diag(A_val_p)
#print(D)

cov1=np.dot(A_vec_p.T,D)
Cov=np.dot((1/2,np.dot(cov1,A_vec_p)))
print(Cov)

vec1=[np.linalg.eig(A)[1][0][1],np.linalg.eig(A)[1][1][1]]
T1=np.dot(A,vec1)
#print(T1)
T2=np.dot(7,vec1)
#print(T2)

[0. 7.]
[-0.8944271909999159, 0.4472135954999579]
[-0.31622776601683794, -0.9486832980505138]
[0. 0.]
[-2.21359436 -6.64078309]


TypeError: dot() missing 1 required positional argument: 'b'

In [84]:




s1=np.zeros([1,2]) 
for k in  range(2):
    for i in range(2):
        s1[0][k]=s1[0][k]+A[i,k]
print(s1)



U=np.zeros([2,2])
for i in  range(2):
    for j in  range(2): 
            U[i,j] =A[i,j]-(1/2)*s1[0][j]
print(U)

                    #calcul de la matrice de covariance

C=np.dot((1/2),np.dot(U.T,U))
print(C)

[[4. 8.]]
[[-1. -2.]
 [ 1.  2.]]
[[1. 2.]
 [2. 4.]]
